### ISSUE TITLE
Alert user when end turn is clicked if there are still moves left

### ISSUE THREAD

**Issue by djwhitt** [Zetawar/zetawar#22]

**Comment by tbeddy** [comment]
I made a version of this that uses a standard JS confirm modal. Would you prefer a React modal instead?

**Comment by djwhitt** [comment]
Yeah, React modal is definitely preferable to JS confirm. I was also contemplating replacing "End Turn?" when clicked and moves are available with "Moves are still available. End turn anyway? yes/no", but I think that might not work so well on mobile devices.

**Comment by tbeddy** [comment]
I only just tried playing on mobile today, and yeah, that would get pretty crowded.

I made a new version with a React modal, but wanted to check what "moves available" means exactly. Does it include whether or not units can be built, or is only about whether existing units can act?

**Comment by djwhitt** [comment]
Good question. I think for the initial version we should probably just consider actions for existing units. Getting notified about the possibility of building is useful too but could get annoying quickly in cases where you're saving up to buy something big.
