### ISSUE TITLE
Add terrain-type/buildable-unit-types

### ISSUE THREAD

**Issue by djwhitt** [Zetawar/zetawar#36]
This will enable bases that only build particular unit types (e.g. airfields and shipyards).

**Comment by abelards** [comment]
That's super awesome!
I've dreamt of advance-wars where you can build bridges to cross rivers
(even if that's super expensive, or we have two types like infantry bridges & vehicles ones).

Is this in the ideas you have? Is commenting on issues the proper way to help/discuss?
Cheers!

**Comment by djwhitt** [comment]
I need to start putting more details on my issues. :smile:

Buildable terrains (e.g. bridges and roads) are definitely planned, but this issue is for unit types that are only buildable on certain types of terrain.

Commenting on or creating issues is definitely fine and probably the best way to communicate about the project at the moment. I do plan to setup a mailing list too, but haven't gotten to it yet.

**Comment by tbeddy** [comment]
This was completed with #87.
