### ISSUE TITLE
Add support for units that can repair other units

### ISSUE THREAD

**Issue by djwhitt** [Zetawar/zetawar#43]
This one is a little involved. To do this you need to:

- [x] Add can-repair (set of armor types) for units types (loaded in [unit-types-tx](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/game.cljs#L1104)).
- [x] Add repair-other action to [:move-attack](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/data.cljs#L91) unit state map.
- [x] Add a unit type that can repair other units (see Elite Command [medic](https://github.com/cvincent/elite-command/blob/c84a3afb3eb2aad3b88c9cc34a7c497caa156010/config/initializers/unit_definitions.rb#L1219)).
- [x] Add a function to check if a unit can repair another unit (see [check-can-repair](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/game.cljs#L648)).
- [x] Add a function to execute a repair transaction (see [repair-tx](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/game.cljs#L665)).
- [x] Add a case to [action-tx](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/game.cljs#L846).
- [x] Add a 'sub' to check whether the currently selected unit can repair the currently selected target (see [can-repair?](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/subs.cljs#L314) and [selected-can-repair?](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/subs.cljs#L400)).
- [x] Add a UI event (see [repair-selected even handler](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/events/ui.cljs#L201)).
- [x] Add a button for repairing a targeted unit (see [faction-actions](https://github.com/Zetawar/zetawar/blob/53d6d49bdba112f02740c6dbd86e732299ec7af4/src/cljs/zetawar/views.cljs#L194)).

I suggest we call the action :action.type/repair-other-unit and the event :zetawar.ui.events/repair-targeted.

**Comment by tbeddy** [comment]
I'm interested in working on this.

**Comment by tbeddy** [comment]
Would you prefer that repairing other units be called something distinct like "heal" or keep it in line with "repair?" I just started digging into the code and wanted to know what you were envisioning.

**Comment by tbeddy** [comment]
Would you prefer that repairing other units be called something distinct like "heal" or keep it in line with "repair?" I just started digging into the code and wanted to know what you were envisioning.

**Comment by djwhitt** [comment]
Glad you're tackling this! I'd say keep it inline with repair. I'll write
up some more general notes on this tomorrow too.

**Comment by tbeddy** [comment]
Cool, looking forward to it.

**Comment by djwhitt** [comment]
I added some tasks to the description to point you in the right direction. It's possible I missed something, but I think that list is pretty complete. I realize it's quite a bit to absorb. Adding a new action to the game is one of the more involved changes you can make. Don't panic though. Just take them one at a time and I'm sure you can get through it. Feel free to ask questions or request code reviews as you go. Good luck!

**Comment by tbeddy** [comment]
Thanks for the description. Should I make the medic images from the elite-command repo?
Edit: I made the medic images and they seem fine.
<img width="326" alt="medic_example" src="https://cloud.githubusercontent.com/assets/4776715/23535675/dd8d1064-ff8d-11e6-8a12-c4710f110631.png">

**Comment by tbeddy** [comment]
There are some bugs, but I have a version of the feature and I'd appreciate your feedback. Would you like to do it through a pull request or just check my repo?

**Comment by djwhitt** [comment]
Nice! A pull request sounds good. That way I can add comments and such.

**Comment by tbeddy** [comment]
I added a couple of commits to my pull request. Sorry for any possible confusion.

**Comment by djwhitt** [comment]
No worries. I'm busy today, but I'll take look tomorrow and give you some
feedback.

**Comment by tbeddy** [comment]
This issue should probably be closed now.
