### ISSUE TITLE
Display terrain effects for selected and targeted terrains

### ISSUE THREAD

**Issue by djwhitt** [Zetawar/zetawar#55]
Should display movement cost, attack bonus, and defense bonus.

**Comment by tbeddy** [comment]
Should this only be visible if both a unit is a selected and a terrain that can be moved to is targeted?

**Comment by tbeddy** [comment]
For some context: should the terrain effects be visible for a selected unit if nothing is targeted? If so, should these terrain effects disappear if a unit is targeted (enemy or friendly)?

**Comment by djwhitt** [comment]
Ideally I think we should show all that information. In other words, terrain effects for the currently selected unit, targeted terrain (without unit), and targeted terrain (with enemy unit). I guess I don't care too much if a friendly unit is targeted for healing, but it wouldn't hurt to show it then too. This will obviously require a fairly compressed format. Also, in terms of location, I'm imagining this showing up below the map.
