### ISSUE TITLE
Disable self-repair by default (limit self-repairs to bases)

### ISSUE THREAD

**Issue by djwhitt** [Zetawar/zetawar#59]
Still debating this a bit, but I think with the addition of units that can repair/heal, self-repair anywhere on the map should be disabled and replaced with self-repair only on certain tiles (bases and possibly repair bays). The amount of the repair should (probably?) also be determined by the terrain type.

**Comment by tbeddy** [comment]
Only allowing self-repair on bases appears to follow Elite Command's rules, but determining repair value by terrain type doesn't. How much variance are you imagining between terrain types?

**Comment by djwhitt** [comment]
I'm not sure yet. The use case for basing it on terrain type is repair bays. We might want them to repair a different amount compared to bases.

Looking at Elite Command, it appears to do a very generous 1/2 damage heal on bases. That seems like too much to me, but something based on a ratio rather than a fixed amount could be interesting. I might defer the decision on the amount for the initial implementation and keep the existing logic but confine it to bases.

**Comment by djwhitt** [comment]
I think I'll probably split this up into a multiple issues with a minimal version targeted for the next release.

**Comment by djwhitt** [comment]
I think the critical functionality for the next release is limiting self-healing to bases. We can generalize how it works for other terrain types later. I'm just concerned that self-healing everywhere + units that can heal weights things to heavily towards defense. We can also skip making healing ratio based for now.

**Comment by djwhitt** [comment]
Forgot to mention this issue in the commit message, but this is complete as of 338083f143f9746d138c1e435e3acc308936f6be
