### ISSUE TITLE
Remove event router dependency on Reagent

### ISSUE THREAD

**Issue by djwhitt** [Zetawar/zetawar#94]
The goal with this is to be able to run the event router without any UI. This should be possible by moving the Reagent specific code into callbacks that are passed into the router when starting it.

**Comment by tbeddy** [comment]
The only Reagent specific code that needs to be moved is the single use of `next-tick` in `router.cljs`, right?

**Comment by djwhitt** [comment]
Yep, the amount of code is trivial. The bigger question is how to make the interface generic so next-tick could be replaced with equivalent functionality from another rendering engine.

**Comment by djwhitt** [comment]
Not the most elegant solution, but it'll do for now. Hopefully something better emerges over time.
