### ISSUE TITLE
Add new map to show off water/naval units

### ISSUE THREAD

**Issue by tbeddy** [Zetawar/zetawar#96]
Zetawar currently has two built-in maps, neither of which gives very much room (if any) for ships. A new default map should include a significant number of deep-water and shallow-water terrains, though not enough for naval combat to dominate gameplay.

**Comment by tbeddy** [comment]
@djwhitt Would using one of the default maps from Elite Command be okay for this? We'd obviously add credit in the code and probably in the UI too. I was thinking of writing a cljs script for lumo to convert EC maps for ZW.

**Comment by djwhitt** [comment]
Sure, pulling in an Elite Command map would be great. We should probably add something to the map data structure to support attribution. A Lumo converter sounds cool too.

**Comment by tbeddy** [comment]
EC includes a description for each of its maps. For example, "Little Island" has "A tiny war on a tiny island." Should I include this info? We could change :description to :title in our map data structure to accommodate this.

**Comment by djwhitt** [comment]
Yep, that sounds reasonable. Though, I'd like to keep the new more verbose description optional.

**Comment by tbeddy** [comment]
Do you mean not load it into the DB at all, or just use something else (like the title or a blank string) if a description isn't available?

**Comment by djwhitt** [comment]
Not loading it into the DB at all if it's missing is probably best. The UI should also gracefully handle a lack of description.

**Comment by tbeddy** [comment]
I'm thinking of using something like `:notes` for the longer description instead. I don't like how `:title`/`:description` breaks with every other use of `:description`.

**Comment by djwhitt** [comment]
Agreed, I like that better. I was a little uncomfortable with :title / :description too, but didn't have a better idea. I'm glad you thought of one.
